### ISSUE TITLE
Težave pri registraciji

### ISSUE THREAD

**Issue by AnjaTrobec** [AnjaTrobec/OPB-e-knjiznica#1]
Zdravo, naleteli smo na naslednje težave:
- pri registraciji gre najverjetneje za napako v kodi znotraj glavne datoteke eknjiznica.py, vendar sami ne odkrijemo napake,
- pri vstopu v eKnjižnico se v tabeli pojavi možnost izposoje ali nakupa knjige. Želeli bi, da se s pritiskom na gumb 'Kupi' knjiga doda v osebno knjižnico uporabnika, vendar tega ne znamo povezati. Trenutno je osebna knjižnica uporabnika kar enaka kot celotna knjižnica, kar pa seveda ni ok. 
- težavo imamo tudi pri brisanju uporabniškega računa, saj se ob pritisku na gumb 'Izbriši moj profil' ne zgodi nič. Tudi tukaj ne najdemo napake. 

Razmišljamo o tem, da bi izbrisali cene in bi si lahko vsak uporabnik izposojal in kupoval (morda celo samo izposojal) povsem prosto. Če menite, da bo potem projekt preveč preprost nam prosim povejte. 

Najlepša hvala za pomoč!

**Comment by jaanos** [comment]
S commitom 5cb9963fd544158cf35407983e9337e69ff30df1 se aplikacija sploh ni zagnala - težava je tukaj:
https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/5cb9963fd544158cf35407983e9337e69ff30df1/eknjiznica.py#L235-L237
Vidim sicer, da je v zadnjem commitu celotna funkcija zakomentirana.

Tukaj imate namreč stavek `try` brez stavka `except`, zaradi česar pride do skladenjske napake. Poleg tega tudi SQL stavek ni v redu - če želite preveriti, da sta tako uporabniško ime kot e-naslov enaka podanima, podajte oba pogoja, ločena z `AND` (ali pa morda z `OR`, če preverjate, če je v bazi že uporabnik z navedenim uporabniškim imenom ali e-naslovom).

Najprej glede same baze. Svetoval bi, da v tabeli `uporabnik` daste omejitev `UNIQUE` na stolpec `username` (ter morda tudi `email`), da se uporabniška imena ne bodo mogla podvajati (potem tudi ni potrebno preverjati, ali uporabnik že obstaja, pač pa samo preverite za napako pri dodajanju). Poleg tega manjka še glavni ključ v tabeli `ocena` - ta naj sestoji iz obeh tujih ključev. Kar se tiče cen, se baza ne bo bistveno poenostavila, če jih izpustite, tako da sami presodite, če se vam zdi to smiselno.

Sicer pa registracija ne deluje, ker pred dodajanjem uporabnika najprej preverite, ali uporabnik obstaja, in če ne, vrnete napako. V primeru, da uporabnik obstaja, pa mu zamenjate geslo s podanim, nato pa naredite preusmeritev, zaradi česar do dodajanja uporabnika nikoli ne pride (klic funkcije `redirect` sproži izjemo, tako da se sledeče vrstice ne izvedejo - posebej to pomeni, da za `redirect` ni potrebno končati funkcije z `return`). Smiselno bi bilo seveda najprej preveriti, ali uporabnik že obstaja (lahko pa to izpustite - glejte zgoraj), nato preverite ustreznost gesla, nazadnje pa vstavite uporabnika v bazo (spreminjanje gesla je tukaj seveda odveč - seveda pa pri vstavljanju v bazo vpišite zgostitev gesla). Pazite tudi pri klicu metode `set_cookie`, saj pri registraciji manjka ime piškotka (tj., dodajte prvi parameter `'username'`).

Mimogrede, dobro bi bilo poskrbeti, da se po neuspešni registraciji (pa tudi pri drugih obrazcih) polja znova zapolnijo z vpisanim (to lahko naredite na podoben način kot za opozorila - seveda potem tudi poskrbite za brisanje piškotkov po uspešni registraciji). Pri prijavi ne pozabite na zgoščevanje gesla (seveda bo potrebno to poskrbeti tudi pri obstoječih geslih). Poskrbite tudi, do katerih strani lahko dostopajo prijavljeni in neprijavljeni uporabniki (npr. prijavljeni uporabnik ne more dostopati do prijave in registracije, neprijavljeni pa ne do osebne knjižnice).

Kar se tiče kupovanja, to zaenkrat ne deluje - na hitro bi funkcijo lahko popravili tako:
```python
@post('/knjiznica/kupi/<id_knjige:int>')
def kupi_knjigo(id_knjige):
    oseba = preveriUporabnika()
    id_uporabnika = oseba[1]
    cur = baza.cursor()
    cur.execute("INSERT INTO transakcija (id_uporabnika, id_knjige, tip, datum) VALUES (%s, %s, 'nakup', now())", (id_uporabnika, id_knjige))
    redirect(url('moja_knjiznica_get'))
```
Tukaj je v predlogi poti navedeno, da je `id_knjige` celo število - sicer se vrednost poda kot niz in bi jo bilo potrebno ročno pretvoriti v število pred vstavljanjem v poizvedbo. Za datum se tukaj uporabi SQL-jeva funkcija `now()` - še lepše bi bilo, če bi to bila privzeta vrednost stolpca `datum`, da je tukaj ni potrebno navajati.

Kar se tiče prikaza osebne knjižnice, bi bilo potrebno pri obstoječi poizvedbi dodati še pogoj, da je uporabnik kupil to knjigo, npr.
```sql
SELECT id_knjige, naslov, avtor.ime FROM knjige
INNER JOIN avtor ON avtor.id_avtorja = knjige.id_avtorja
WHERE id_knjige IN (
  SELECT id_knjige FROM transakcije
  WHERE id_uporabnika = %s AND tip = 'nakup'
);
```
Tako se bodo prikazale le kupljene knjige - verjetno želite nekako obravnavati tudi izposojene.

Da bo gumb za brisanje profila deloval, naj bo znotraj obrazca (podobno kot gumb za registracijo na strani za prijavo - slednjega bi bilo sicer bolje nadomestiti z običajno povezavo, da do obrazca dostopate z metodo `GET`). ID-ja uporabnika v poti za brisanje sicer ni smiselno imeti, saj se ta ne uporabi, pač pa se pobriše trenutno prijavljeni uporabnik. Da bo brisanje uporabnika mogoče, bo potrebno pred tem pobrisati še njegove ocene in transakcije. Če se odločite za to, potem bo bolje, da pobrišete vrstico
https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/ba8bea6c41e91e6fd55fe05a34e2134a6bd33c51/eknjiznica.py#L314
in po vsaki uspešni spremembi baze kličete `baza.commit()`, da se spremembe zapišejo, ob napakah pa `baza.rollback()`, da se transakcija zavrže (pri brisanju uporabnika bi tako imeli tri stavke `DELETE` - `baza.commit()` kličete šele, ko se vsi trije uspešno izvedejo).

Mimogrede, svetujem, da namesto navajanja poti (tako v predlogah kot pri klicih funkcije `redirect` - glejte zgornji primer) uporabite funkcijo `url` - tej kot prvi argument podaste niz z imenom ustrezne funkcije, nato pa s poimenovanimi parametri podaste še ostale podatke. Tako namesto
https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/ba8bea6c41e91e6fd55fe05a34e2134a6bd33c51/views/base.html#L12
raje naredite
```html
<script src="{{url('static', filename='knjiznica.js')}}"></script>
```
in podobno pri vseh povezavah, obrazcih, stilih itd. Tako lahko potem poskrbite, da bo aplikacija tekla tudi na Binderju - potrebno bo skopirati še mapo [`binder`](https://github.com/jaanos/OPB-bottle/tree/master/binder) z vzorčnega repozitorija in v `start` popraviti še ime glavnega programa.

**Comment by AnjaTrobec** [comment]
Zdravo! Najlepša hvala za odgovor in pomoč. Večino smo popravili, težavo imamo le z naslednjim odstavkom: 

Mimogrede, dobro bi bilo poskrbeti, da se po neuspešni registraciji (pa tudi pri drugih obrazcih) polja znova zapolnijo z vpisanim (to lahko naredite na podoben način kot za opozorila - seveda potem tudi poskrbite za brisanje piškotkov po uspešni registraciji). Pri prijavi ne pozabite na zgoščevanje gesla (seveda bo potrebno to poskrbeti tudi pri obstoječih geslih). Poskrbite tudi, do katerih strani lahko dostopajo prijavljeni in neprijavljeni uporabniki (npr. prijavljeni uporabnik ne more dostopati do prijave in registracije, neprijavljeni pa ne do osebne knjižnice).

Torej z nastavitvijo piškotkov. 

Sicer pa smo projekt zaključili in prosimo za vašo odobritev, da lahko pristopimo na zagovor. Še enkrat hvala za pomoč!

**Comment by jaanos** [comment]
Glede na to, da aplikacija deluje, bom dodal povezavo na repozitorij predmeta. Če se še niste, se lahko torej z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Kar se tiče predizpolnjevanja obrazcev (npr. pri registraciji), lahko seveda v ta namen uporabite piškotke.

Imam še sledeče pripombe:

* Stolpec `id_knjige` v tabeli `transakcija` naj bo tuji ključ na tabelo `knjige`.
* Gesla v bazi shranjujete v čisti obliki, čeprav imate na voljo funkcijo `hashGesla` za njihovo zgoščevanje. Poskrbite torej, da se pri registraciji namesto `password` vnese vrednost `zgostitev` (stavek `UPDATE` pred vstavljanjem je odveč), pri prijavi pa iz vnesenega gesla izračunate zgostitev in dobljeno vrednost primerjate z vrednostjo v bazi. Seveda bo potrebno obstoječe gesla v bazi nadomestiti z zgostitvami.
* Pri zunanjih URL-jih je uporaba `url` odveč:
  https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/d38ae5ac550c5270231610398bfaa396b68dfbaa/views/base.html#L40-L42
  Namesto tega funkcijo `url` (tako kot ste jo uporabili za nalaganje JavaScripta in slike) uporabite pri vseh lokalnih poteh v vseh predlogah (torej pri vseh `<a href="...">` in `<form action="...">` - morda sem še kaj spregledal). Tako namesto
  https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/d38ae5ac550c5270231610398bfaa396b68dfbaa/views/moje_knjige.html#L27
  naredite
  ```html
  <form action="{{url('vrni_knjigo', id_knjige=id_knjige}}" method="post">
  ```
  in podobno drugod. Ko to uredite, bi morala aplikacija delovati na Binderju, kar lahko preverite na naslovu   https://mybinder.org/v2/gh/AnjaTrobec/OPB-e-knjiznica/main?urlpath=proxy/8080/. Ko bo delovala, lahko v `README.md` dodaste še sliko s povezavo za zagon v Binderju:
  ```markdown
  [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/AnjaTrobec/OPB-e-knjiznica/main?urlpath=proxy/8080)
  ```

**Comment by AnjaTrobec** [comment]
Najlepša hvala za pomoč. Naredili smo še zadnji commit, tako da vas prosimo, da za oddan izdelek izberete trenutno verzijo projekta.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.

Še eno malenkost sem opazil: ko se nastavi opozorilo, se bo to prikazovalo, dokler ne bo nastavljeno drugo opozorilo. Da se to ne bi dogajalo, bi bilo potrebno piškotek z opozorilom pobrisati takoj, ko se opozorilo prikaže,

**Comment by jaanos** [comment]
Aha, vidim, da to sicer že počnete, vendar bo potrebno popraviti, da bo delovalo pravilno:
https://github.com/AnjaTrobec/OPB-e-knjiznica/blob/c66e04255d4608de63ac9cbf9cd3149d31c12cb9/eknjiznica.py#L36
Tako kot pri nastavljanju sporočila bo potrebno dodati še parameter `path="/"` - lahko ga pa tam odstranite (pri nastavljanju uporabniškega imena ga nimate).

**Comment by AnjaTrobec** [comment]
Sem popravila, hvala!

**Comment by jaanos** [comment]
Zdaj odjava ne deluje pravilno - po kliku na *Odjava* je še vedno možno priti do profila in osebne knjižnice. Dodatni parameter pri brisanju uporabniškega imena ni potreben, saj tudi pri nastavljanju ni bil uporabljen. Morda bo najbolje, če ga kar povsod pobrišete (tj., tako pri nastavljanju kot pri brisanju piškotkov).

**Comment by AnjaTrobec** [comment]
Če ga povsod pobrišem se sporočila ne pojavijo več. Vsaj ne, če program direktno poženem preko localhost:8080.

**Comment by jaanos** [comment]
Aha, potem pa bo očitno bolje, če se ga povsod doda (tj., tudi pri nastavljanju uporabniškega imena). Kakorkoli, bodisi je (za posamezen piškotek) tako pri nastavljanju kot pri brisanju, ali pa nikjer.

**Comment by AnjaTrobec** [comment]
Zdaj pa štima, hvala!

**Comment by jaanos** [comment]
Super, sem znova posodobil povezavo.
